# Generated by Django 5.0 on 2024-05-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0008_merge_20240513_0013'),
        ('The_Investor', '0019_alter_investorratingcomment_rating'),
    ]

    operations = [
    ]
