# Generated by Django 5.0 on 2024-05-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0020_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Investor.investor'),
        ),
    ]
